@api = http://localhost:3000/api/tasks

### Get Tasks
GET {{api}}

### Create a new Task
POST {{api}}
Content-Type: application/json

{
  "title": "my four task",
  "description": "my four task"
}

### Get Single Task
GET {{api}}/5fc500819bf75f1ffdc48da7

### Update
PUT {{api}}/5fc500819bf75f1ffdc48da7
Content-Type: application/json

{
  "title": "Title Updated",
  "description": "my updated description",
  "done": false
}

### Get Tasks and search
GET {{api}}?title=up

### Get all Done tasks
GET {{api}}/done

### DELETE Single Task
DELETE {{api}}/5fc500819bf75f1ffdc48da7

### DELETE all tasks
DELETE {{api}}